### ISSUE TITLE
BigWig step does not run for genomes/annotations without the 'chr' chromosome prefix

### ISSUE THREAD

**Issue by emi80** [guigolab/grape-nf#17]

**Comment by karl616** [comment]
I also stumbled upon this problem. I think it is due to the "--outWigReferencesPrefix chr" flag in the STAR command to generate the initial bedGraph files. It will limit the process to chromosomes/contigs matching the given regular expression.

**Comment by emi80** [comment]
Hi @karl616,

this issue has not been addressed yet since it has not been a priority for us. However, I think that now that the pipeline could be used by a wider audience a fix is required.

I was thinking about setting the regular expression with a pipeline parameter (`--refPrefix` or similar). For backward compatibility `chr`should be the default and, following STAR documentation, a `-` will be used to include all references. If needed, I might also provide aliases to common/complex regular expressions.

**Comment by karl616** [comment]
Hi @emi80 

I'm processing mouse data from time to time and the reference we use currently is without the chr prefix. I would be happy with the solution you suggest.

**Comment by emi80** [comment]
It seems that `STAR` `--outWigReferencesPrefix` does not accept a regular expression as the argument, since a string comparison is performed internally (see [here](https://github.com/alexdobin/STAR/blob/82020fadb2a34dff39884fa5b10fda2f0984bae9/source/signalFromBAM.cpp#L20)).

The pipeline parameter `--wig-ref-prefix` is already there but was not documented because of the above behaviour. I need to think about a proper fix for this. 

The workaround for now would be run the pipeline with `--wig-ref-prefix -` to allow all references to be included in the signal files.

**Comment by karl616** [comment]
I don't need the regular expression, but I can definitely see cases when it can be beneficial. I will use wig-ref-prefix for now

**Comment by karl616** [comment]
Now, first now, did I really understand the code. The fix was there all the time :)
