### ISSUE TITLE
List of software versions

### ISSUE THREAD

**Issue by karl616** [guigolab/grape-nf#18]
Would it be possible to include a list of required software with versions?

In principle I find the docker solution excellent, but I would need to run the pipeline on a cluster on which I'm not allowed to use docker. I already got it running, but I'm sure I don't have the right versions of every software.

**Comment by emi80** [comment]
Hi, @karl616. Thanks for this. 

I agree with you it would be useful to have a list of software versions needed to run the pipeline. I will add a section to the readme.

**Comment by karl616** [comment]
Thank you very much. In the meantime I found the list circulated within IHEC. I did indeed have a couple of mismatching versions

**Comment by karl616** [comment]
Thank you!
