### ISSUE TITLE
Read 1 decided by order of index file, not FqRd1/FqRd2 (Bug?)

### ISSUE THREAD

**Issue by karl616** [guigolab/grape-nf#21]
The way I read the documentation I thought the file containing Mate/Read 1 was decided by the FqRd1 tag ==> I didn't care about the order of my index file and it was sometimes jumbled. Analyzing a set experiments I ended up with a mixture of MATE1_SENSE, MATE2_SENSE and NONE assignments. This was incorrect.

It seems the first read in the index file is treated as Mate 1, independent of what is given in the view column (column 5).

I think it comes down to this:
https://github.com/guigolab/grape-nf/blob/b0445ac8a62f61190b0d04e8eed2e16bd43dcd71/grape-pipeline.nf#L166
Column 5 is never taken into account. For me, this is not intuitive.

Example:
One sample with two pairs of fastq files:

index:
```
sample A read1_001.fq.gz fastq FqRd1
sample A read2_001.fq.gz fastq FqRd2
sample B read2_002.fq.gz fastq FqRd2
sample B read1_002.fq.gz fastq FqRd1
```
==> resulting alignment step

```
A:
STAR .... --readFilesIn read1_001.fq.gz read2_001.fq.gz ....
B:
STAR .... --readFilesIn read2_002.fq.gz read1_002.fq.gz ....

```
B is wrong

Solutions:
- Make excruciatingly clear in the documentation that the index file have to be sorted
- Make use of the information in column 5?

I would prefer the latter solution and would have submitted a patch, but this goes a bit to deep into python/nextflow for me to feel comfortable. I will sort my index files from now on.

**Comment by emi80** [comment]
Thanks @karl616. 

This is definitely a bug. The information from column five has to be used to sort the pairs. We never had this problem since our index files are always sorted. 

Fortunately, the problem is quite easy to solve and I will push a fix later today.
