### ISSUE TITLE
Citation information

### ISSUE THREAD

**Issue by karl616** [guigolab/grape-nf#38]
Hi,
our first project with grape-nf has reached the publication phase and I was wondering if you have a preferred way for citing?
Otherwise I will refer to this github repository...
Googling and thinking a bit I came up with https://zenodo.org/

Best,
Karl

**Comment by emi80** [comment]
Hi Karl,

I really appologize for the late reply.

For now please just use the link to the GitHub repository as you mentioned,
since we don't have a publication for grape-nf.

Best,
Emilio

**Comment by karl616** [comment]
Thanks, that was what I settled on in the end. 

So far it is only submission so far and I will try to check again before it goes into print.

**Comment by emi80** [comment]
Sounds good! 👍

**Comment by emi80** [comment]
Linked repo to Zenodo for citation
